"""Switch from Stat to Rank

Revision ID: 12aa7a338973
Revises: c9d5d86cb497
Create Date: 2016-11-15 15:53:52.784273

"""

# revision identifiers, used by Alembic.
revision = '12aa7a338973'
down_revision = 'c9d5d86cb497'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rank_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stat')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('profile_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('stat_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], [u'profile.id'], name=u'stat_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('rank')
    ### end Alembic commands ###
