"""migrate rank_date to datetime

Revision ID: 26f0d5cacb87
Revises: 12aa7a338973
Create Date: 2016-11-16 10:35:54.623731

"""

# revision identifiers, used by Alembic.
revision = '26f0d5cacb87'
down_revision = '12aa7a338973'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
     op.alter_column(
        table_name='rank',
        column_name='rank_date',
        nullable=True,
        type_=sa.DateTime()
     )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
     op.alter_column(
        table_name='rank',
        column_name='rank_date',
        nullable=True,
        type_=sa.Date()
     )
    ### end Alembic commands ###
