"""adding more data to rank

Revision ID: 708d13bad339
Revises: 26f0d5cacb87
Create Date: 2016-11-16 11:54:10.147741

"""

# revision identifiers, used by Alembic.
revision = '708d13bad339'
down_revision = '26f0d5cacb87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank', sa.Column('avatar', sa.String(255), nullable=True))
    op.add_column('rank', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('rank', sa.Column('portrait', sa.String(255), nullable=True))
    op.add_column('rank', sa.Column('rank_img', sa.String(255), nullable=True))
    op.add_column('rank', sa.Column('star', sa.String(255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rank', 'star')
    op.drop_column('rank', 'rank_img')
    op.drop_column('rank', 'portrait')
    op.drop_column('rank', 'level')
    op.drop_column('rank', 'avatar')
    ### end Alembic commands ###
