"""empty message

Revision ID: c9d5d86cb497
Revises: None
Create Date: 2016-11-14 16:38:41.212541

"""

# revision identifiers, used by Alembic.
revision = 'c9d5d86cb497'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.Enum('pc', 'psn', 'xbl', name='platformenum'), nullable=True),
    sa.Column('region', sa.Enum('cn', 'eu', 'gbl', 'kr', 'us', name='regionenum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('stat_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stat')
    op.drop_table('profile')
    ### end Alembic commands ###
